config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :games
  root "statics#index"

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :games, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :get_games

  def get_games
    @games = Game.order("score DESC").limit(5)
  end


# can use method .limit(5)  etc to limit the number of return if desired but
# does not work for high scores because highest score might not be in the 
# first 5 out. 
#
#
#   THIS WORKS BUT GIVES THE LOWEST 5 SCORES:
#    
#   def get_games
#    @games = Game.order("score").limit(5).reverse
#   end
#
#
#
#
#
#
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = current_user.games.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:score, :level, :user_id)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def index
    render text: "", layout: true
  end

  


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end 
  
  def show
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:users).permit(:email)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Games</h1>

<table>
  <thead>
    <tr>
      <th>Score</th>
      <th>Level</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.score %></td>
        <td><%= game.level %></td>
        <td><%= game.user_id %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1></h1>

<!--  <%= render 'form' %> -->

<div id="positioner">
<canvas id="canvas" width="560" height="620">
</div>

<!-- <%= link_to 'Back', games_path %>  -->

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @game.score %>
</p>

<p>
  <strong>Level:</strong>
  <%= @game.level %>
</p>

<p>
  <strong>User:</strong>
  <%= @game.user_id %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

<title>WDiPacMan</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/modernizr" %>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="icon-bar five-up">

    <%= link_to image_tag('fi-home.png')+"Home", root_path %>
    <% if user_signed_in? %>
    <%= link_to image_tag('Logout.png')+"Logout", destroy_user_session_path, method: :delete %> >
    <%= link_to image_tag('PacManMenu.png')+"New Game", new_game_path %> >
    <% else %>
    <%= link_to image_tag("SignIn.png")+"Sign In", new_user_session_path %>
    <%= link_to image_tag('Register.png')+"Register", new_user_registration_path %>
    <% end %>

  </div>
  <div id="scores" >
    <h1>WDI Pacman</h1>
    <h3>HIGH SCORES</h3>
    <% @games.each do |game| %>
    <ul>
      <li><%= game.score %></li>
    </ul>
    <% end %>
  </div>

  <div id="machine">
    <img src="/assets/machine.png">
  </div>

  <div id="machine2">
    <img src="/assets/machine.png">
  </div>


  <!-- <%= link_to "Games", 'games' %> -->

  <%= yield %>

  <div id="picture"><img src="/assets/Pac_man_background_image_clean.png"></div>

  <div id="instructions">
    <p>  </p>
    <p>INSTRUCTIONS:</p>
    <p>Sign in then click on New Game above to start a game</p>
    <p>Use arrow keys to move pacman</p>
    <p>Eat Pac Dots to gain points</p>
    <p>Eat Power Dots to become invincible and gain more points</p>
    <p>Avoid the ghosts or die</p>
    <p>Eat the ghosts when you are invincible for more points</p>
    <p>Invincibility is short lived</p>
    <p>Dead Ghosts still have eyes</p>
    <p>Watch out for Blinky the red ghost, he chases you!</p>
    <p>Pinky, Inky and Clyde are more passive</p>
    <p>written by</p>
    <p>Spencer Meyer, General Assembly 2015</p>
  </div>

  <div id="left"></div>
  <div id="right"></div>
  <div id="top"></div>
  <div id="bottom"></div>

</body>
</html>